import type { CacheSweepDesktopApi, CacheSweepScanResult, CleanupResult } from "./contracts";

const scanFixture: CacheSweepScanResult = {
  platformSupported: true,
  scannedAt: new Date().toISOString(),
  installations: [
    { productId: "premiere-pro", displayName: "Adobe Premiere Pro 2026", version: "26.1", executablePath: null, installLocation: null, source: "hklm-64", confidence: "verified", supportedRuleIds: ["adobe-media-cache"] },
    { productId: "after-effects", displayName: "Adobe After Effects 2026", version: "26.0", executablePath: null, installLocation: null, source: "hklm-64", confidence: "verified", supportedRuleIds: ["adobe-media-cache"] },
    { productId: "lightroom-classic", displayName: "Adobe Lightroom Classic", version: "15.0", executablePath: null, installLocation: null, source: "hklm-64", confidence: "verified", supportedRuleIds: ["camera-raw-cache", "lightroom-previews"] },
    { productId: "illustrator", displayName: "Adobe Illustrator 2026", version: "30.0", executablePath: null, installLocation: null, source: "hklm-64", confidence: "verified", supportedRuleIds: [] },
  ],
  runningProcesses: [],
  categories: [
    {
      ruleId: "adobe-media-cache",
      title: "Media Cache Adobe video",
      applications: ["Adobe Premiere Pro 2026", "Adobe After Effects 2026"],
      risk: "recommended",
      selectedByDefault: true,
      whatIsDeleted: "Audio conformato, forme d'onda, indici e file multimediali temporanei condivisi.",
      consequence: "Le applicazioni ricreeranno i file necessari. La prima apertura dei progetti potrà essere più lenta.",
      warning: null,
      processNames: ["Adobe Premiere Pro.exe", "AfterFX.exe"],
      targets: [{ path: "C:\\Users\\Utente\\AppData\\Roaming\\Adobe\\Common\\Media Cache Files", source: "documented-default", fileCount: 18420, totalBytes: 28_740_000_000, skippedLinks: 0, scanErrors: [] }],
      totalBytes: 28_740_000_000,
      fileCount: 18420,
    },
    {
      ruleId: "camera-raw-cache",
      title: "Camera Raw Cache",
      applications: ["Adobe Lightroom Classic"],
      risk: "recommended",
      selectedByDefault: true,
      whatIsDeleted: "Dati temporanei usati da Camera Raw per accelerare l'apertura e lo sviluppo dei file RAW.",
      consequence: "Fotografie, cataloghi e regolazioni restano invariati. Le prime aperture RAW saranno più lente.",
      warning: null,
      processNames: ["Lightroom.exe"],
      targets: [{ path: "C:\\Users\\Utente\\AppData\\Local\\Adobe\\CameraRaw\\Cache", source: "documented-default", fileCount: 3210, totalBytes: 8_220_000_000, skippedLinks: 0, scanErrors: [] }],
      totalBytes: 8_220_000_000,
      fileCount: 3210,
    },
    {
      ruleId: "lightroom-previews",
      title: "Anteprime Lightroom",
      applications: ["Adobe Lightroom Classic"],
      risk: "advanced",
      selectedByDefault: false,
      whatIsDeleted: "Il contenuto dei pacchetti Previews.lrdata trovati nella cartella Lightroom predefinita.",
      consequence: "Lightroom dovrà ricostruire le anteprime; fotografie e modifiche restano intatte.",
      warning: "Opzione avanzata: le anteprime degli originali offline non saranno subito disponibili.",
      processNames: ["Lightroom.exe"],
      targets: [{ path: "C:\\Users\\Utente\\Pictures\\Lightroom\\Catalog Previews.lrdata", source: "discovered-catalog", fileCount: 9400, totalBytes: 12_810_000_000, skippedLinks: 0, scanErrors: [] }],
      totalBytes: 12_810_000_000,
      fileCount: 9400,
    },
  ],
  olderVersions: [
    {
      candidateId: "photoshop-26-fixture",
      productId: "photoshop",
      displayName: "Adobe Photoshop 2025",
      version: "26.11",
      currentVersion: "27.5",
      sapCode: "PHSP",
      baseVersion: "26.0",
      installLocation: "C:\\Program Files\\Adobe\\Adobe Photoshop 2025",
      processNames: ["Photoshop.exe"],
    },
  ],
  warnings: [],
};

export const devApi: CacheSweepDesktopApi = {
  scan: async () => structuredClone(scanFixture),
  closeProcesses: async () => ({ requested: [], closed: [], remaining: [], errors: [] }),
  cleanup: async (ruleIds): Promise<CleanupResult> => ({
    startedAt: new Date().toISOString(),
    completedAt: new Date().toISOString(),
    categories: scanFixture.categories.filter((item) => ruleIds.includes(item.ruleId)).map((item) => ({
      ruleId: item.ruleId,
      title: item.title,
      deletedFiles: item.fileCount,
      deletedBytes: item.totalBytes,
      skippedItems: 0,
      errors: [],
      status: "completed",
    })),
    deletedFiles: scanFixture.categories.filter((item) => ruleIds.includes(item.ruleId)).reduce((sum, item) => sum + item.fileCount, 0),
    deletedBytes: scanFixture.categories.filter((item) => ruleIds.includes(item.ruleId)).reduce((sum, item) => sum + item.totalBytes, 0),
    skippedItems: 0,
    errors: [],
  }),
  uninstallOldVersion: async () => ({
    status: "completed",
    message: "La vecchia versione Adobe è stata rimossa mantenendo le preferenze.",
    remainingProcesses: [],
  }),
};
