import type { DesktopFolderCatalogAssetState, DesktopFolderCatalogState, DesktopLogEvent, DesktopPerformanceSnapshot, DesktopPersistedState, DesktopPhotoSelectorPreferences, DesktopRecentFolder, DesktopSortCacheEntry } from "@photo-tools/desktop-contracts";
export declare function hasDesktopStateApi(): boolean;
export declare function getDesktopPreferences(): Promise<DesktopPhotoSelectorPreferences | null>;
export declare function saveDesktopPreferences(preferences: DesktopPhotoSelectorPreferences): Promise<DesktopPhotoSelectorPreferences | null>;
export declare function getDesktopSessionState(): Promise<DesktopPersistedState | null>;
export declare function saveDesktopSessionState(state: DesktopPersistedState): Promise<boolean>;
export declare function getDesktopRecentFolders(): Promise<DesktopRecentFolder[] | null>;
export declare function saveDesktopRecentFolder(folder: DesktopRecentFolder): Promise<DesktopRecentFolder[] | null>;
export declare function removeDesktopRecentFolder(folderPathOrName: string): Promise<DesktopRecentFolder[] | null>;
export declare function getDesktopSortCache(folderPath?: string): Promise<DesktopSortCacheEntry[] | null>;
export declare function saveDesktopSortCache(entry: DesktopSortCacheEntry): Promise<boolean>;
export declare function getDesktopFolderCatalogState(folderPath: string): Promise<DesktopFolderCatalogState | null>;
export declare function saveDesktopFolderCatalogState(state: DesktopFolderCatalogState): Promise<boolean>;
export declare function saveDesktopFolderAssetStates(folderPath: string, assetStates: DesktopFolderCatalogAssetState[]): Promise<boolean>;
export declare function getDesktopPerformanceSnapshot(): Promise<DesktopPerformanceSnapshot | null>;
export declare function recordDesktopPerformanceSnapshot(snapshot: DesktopPerformanceSnapshot): Promise<boolean>;
export declare function logDesktopEvent(event: DesktopLogEvent): Promise<boolean>;
