// Generated by scripts/setup-filex-attestation-key.mjs. Public verification key only.
export const FILEX_LICENSE_PUBLIC_KEY = "-----BEGIN PUBLIC KEY-----\nMCowBQYDK2VwAyEAT3qdjphJLO/lc1II7KhriM/GIVD4oeyuLv9UYmLVrhc=\n-----END PUBLIC KEY-----\n";
