import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
export function ImportProgressModal({ isOpen, phase, supported, ignored, total, processed, currentFile, folderLabel }) {
    if (!isOpen) {
        return null;
    }
    const safeTotal = Math.max(total, 1);
    const progressPercent = phase === "reading" ? 8 : Math.round((processed / safeTotal) * 100);
    const phaseTitle = phase === "reading" ? "Lettura cartella" : "Preparazione anteprime";
    const phaseDescription = phase === "reading"
        ? "Sto controllando la cartella selezionata e contando le immagini supportate."
        : "Sto preparando anteprime e metadati delle foto per la schermata selezione.";
    return (_jsx("div", { className: "modal-backdrop", children: _jsxs("div", { className: "modal-panel modal-panel--import", role: "dialog", "aria-modal": "true", "aria-labelledby": "import-progress-title", children: [_jsx("div", { className: "modal-panel__header", children: _jsxs("div", { children: [_jsx("h2", { id: "import-progress-title", children: "Caricamento foto in corso" }), _jsx("p", { children: folderLabel || "Preparazione cartella selezionata" })] }) }), _jsxs("div", { className: "modal-panel__body import-progress", children: [_jsxs("div", { className: "import-progress__phase", children: [_jsx("span", { className: phase === "reading" ? "import-progress__phase-pill import-progress__phase-pill--active" : "import-progress__phase-pill", children: "1. Lettura cartella" }), _jsx("span", { className: phase === "preparing" ? "import-progress__phase-pill import-progress__phase-pill--active" : "import-progress__phase-pill", children: "2. Preparazione anteprime" })] }), _jsxs("div", { className: "import-progress__summary", children: [_jsx("strong", { children: phase === "reading" ? "Analisi cartella in corso" : `${processed} di ${total} immagini pronte` }), _jsxs("span", { children: [progressPercent, "%"] })] }), _jsxs("div", { className: "import-progress__counts", children: [_jsxs("span", { children: [supported, " immagini supportate"] }), _jsxs("span", { children: [ignored, " ignorate"] })] }), _jsx("div", { className: "progress-bar", "aria-hidden": "true", children: _jsx("div", { className: "progress-bar__fill", style: { width: `${progressPercent}%` } }) }), _jsxs("div", { className: "import-progress__status", children: [_jsx("span", { children: phaseTitle }), _jsx("strong", { children: currentFile ?? phaseDescription })] }), _jsx("p", { className: "import-progress__hint", children: phaseDescription })] }), _jsx("div", { className: "modal-panel__footer", children: _jsx("button", { type: "button", className: "ghost-button", disabled: true, children: "Importazione in corso..." }) })] }) }));
}
//# sourceMappingURL=ImportProgressModal.js.map