import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { createPortal } from "react-dom";
import { COLOR_LABEL_NAMES, COLOR_LABELS, getColorShortcutHint, PICK_STATUS_LABELS, } from "../services/photo-classification";
export function PhotoSelectionContextMenu({ x, y, targetCount, colorLabelNames = COLOR_LABEL_NAMES, onApplyRating, onApplyPickStatus, onApplyColor, onInvertVisible, onClearSelection, }) {
    const menu = (_jsxs("div", { className: "selection-context-menu", style: { left: `${x}px`, top: `${y}px` }, onMouseDown: (event) => event.stopPropagation(), role: "menu", "aria-label": targetCount === 1
            ? "Menu contestuale della foto selezionata"
            : `Menu contestuale per ${targetCount} foto selezionate`, children: [_jsxs("div", { className: "selection-context-menu__header", children: [_jsx("strong", { children: targetCount === 1 ? "1 foto selezionata" : `${targetCount} foto selezionate` }), _jsx("span", { children: "Valutazione, stato, etichetta e gestione selezione." })] }), _jsxs("div", { className: "selection-context-menu__section", children: [_jsx("span", { className: "selection-context-menu__label", children: "Valutazione" }), _jsxs("div", { className: "selection-context-menu__stars", children: [[1, 2, 3, 4, 5].map((value) => (_jsx("button", { type: "button", className: "selection-context-menu__star", onClick: () => onApplyRating(value), role: "menuitem", children: Array.from({ length: value }, () => "★").join("") }, value))), _jsx("button", { type: "button", className: "selection-context-menu__ghost", onClick: () => onApplyRating(0), role: "menuitem", children: "Azzera stelle" })] })] }), _jsxs("div", { className: "selection-context-menu__section", children: [_jsx("span", { className: "selection-context-menu__label", children: "Stato" }), _jsx("div", { className: "selection-context-menu__pills", children: ["picked", "rejected", "unmarked"].map((value) => (_jsx("button", { type: "button", className: "selection-context-menu__pill", onClick: () => onApplyPickStatus(value), role: "menuitem", children: PICK_STATUS_LABELS[value] }, value))) })] }), _jsxs("div", { className: "selection-context-menu__section", children: [_jsx("span", { className: "selection-context-menu__label", children: "Etichetta colore" }), _jsxs("div", { className: "selection-context-menu__colors", children: [_jsx("button", { type: "button", className: "selection-context-menu__ghost", onClick: () => onApplyColor(null), role: "menuitem", children: "Rimuovi colore" }), COLOR_LABELS.map((value) => (_jsx("button", { type: "button", className: `asset-color-dot asset-color-dot--${value}`, title: `${colorLabelNames[value]} | ${getColorShortcutHint(value)}`, onClick: () => onApplyColor(value), role: "menuitem" }, value)))] })] }), _jsxs("div", { className: "selection-context-menu__section", children: [_jsx("span", { className: "selection-context-menu__label", children: "Selezione" }), _jsxs("div", { className: "selection-context-menu__actions", children: [_jsx("button", { type: "button", className: "selection-context-menu__ghost", onClick: onInvertVisible, role: "menuitem", children: "Inverti visibili" }), _jsx("button", { type: "button", className: "selection-context-menu__ghost", onClick: onClearSelection, role: "menuitem", children: "Deseleziona tutto" })] })] })] }));
    if (typeof document === "undefined") {
        return menu;
    }
    return createPortal(menu, document.body);
}
//# sourceMappingURL=PhotoSelectionContextMenu.js.map