// Generated by scripts/bootstrap-paypal-commerce.mjs after PayPal onboarding.
// Public PayPal identifiers only; never place secrets here.
export const FILEX_COMMERCE_DEFAULTS = {
  "enforcement": "observe",
  "paypalEnvironment": "sandbox",
  "paypalClientId": "BAAL-2RVd6NZ2HmEm2VerMRP8q8c2BF_LM-ryheN3CJIyyVL-janmpSM-SII4T5GdwaDMWyun5ct7ceIZU",
  "paypalWebhookId": "1V535209KR777192D",
  "paypalMonthlyPlanId": "P-6SY843431U323725JNKEXWZQ",
  "paypalAnnualPlanId": "P-3FX52263K1081762PNKEXWZY"
} as const;
