// Generated by scripts/bootstrap-filex-commerce.mjs after merchant onboarding.
// Public identifiers and hosted checkout URLs only; never place secrets here.
export const FILEX_COMMERCE_DEFAULTS = {
  enforcement: "observe" as const,
  allowedVariantIds: [] as string[],
  checkoutMonthlyUrl: null as string | null,
  checkoutAnnualUrl: null as string | null,
};
